#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
feh --bg-fill ~/wallpapers/ign-waifu.png
# feh --bg-scale ~/Pictures/abdelrehem.jpg
xsetroot -cursor_name left_ptr
~/.config/polybar/launch.sh &
kdeconnect-indicator &
picom &
dunst &
copyq &
~/.config/bspwm/packages_update &

redshift -P -m randr -l 30:31.2 -t 6500:5000 &

bspc monitor -d         

bspc config border_width         2
bspc config window_gap           10

bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config paddingless_monocle true
bspc config single_monocle false

bspc config active_border_color "#e83a3f"
bspc config focused_border_color "#b03648"
bspc config normal_border_color "#373b41"

bspc rule -a obsidian desktop='^6' follow=on
bspc rule -a Gimp-2.10 desktop='^7' state=floating follow=on
bspc rule -a Pavucontrol state=floating follow=on
bspc rule -a TelegramDesktop desktop='^3' follow=on  
bspc rule -a discord desktop='^3' follow=on 
bspc rule -a Caja desktop='^9' follow=on
bspc rule -a firefox desktop='^1' follow=on
bspc rule -a vlc desktop='^4' follow=on
bspc rule -a mpv desktop='^4' follow=on
bspc rule -a 'Minecraft* 1.19.3' desktop='^8' follow=on
bspc rule -a copyq state=floating
bspc rule -a Brave-browser desktop='^1' follow=on
bspc rule -a xdman-Main state=floating
bspc rule -a qBittorrent state=floating desktop='^6' follow=on
bspc rule -a okular desktop='^7' follow=on
bspc rule -a scrcpy follow=on state=pseudo_tiled
bspc rule -a 'ONLYOFFICE Desktop Editors' desktop='^6' follow=on
bspc rule -a 'SimpleScreenRecorder' desktop='^7' follow=on state=floating
bspc rule -a 'altaqwaa' follow=on state=floating
bspc rule -a 'Zathura' state=tiled
bspc rule -a 'Spotify' desktop='^5' follow=on
